apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-user
  template:
    metadata:
      labels:
        app: fastapi-user
    spec:
      containers:
      - image: sa-service-2
        imagePullPolicy: Never
        name: sa-service-2
        envFrom:
        - secretRef:
            name: psql-postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: service-two-service
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: fastapi-user
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-two-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-two-service
            port: 
              number: 80
